import org.as2lib.env.reflect.ClassInfo;

/**
 * Interface for each as2lib class.
 * This interface shows the basic Methods a class within the as2lib should have.
 * @see org.as2lib.core.BasicClass
 */
interface org.as2lib.core.BasicInterface {       
     /** 
      * Returns a ClassInformation generated by the acutal instance. 
      * @throws org.as2lib.env.reflect.ReferenceNotFoundException if no reference of the class was found. 
      */ 
     public function getClass(Void):ClassInfo; 
}